server:
  port: 8081

spring:
  application:
    name: USER-SERVICE

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/User-Hotel-Rating
    username: postgres
    password: pgAdmin
    driverClassName: org.postgresql.Driver  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  