server:
  port: 8082

spring:
  application:
    name: HOTEL-SERVICE

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/User-Hotel-Rating
    username: postgres
    password: pgAdmin
    driverClassName: org.postgresql.Driver  
   